name: API Transformer
dbless_compatible: yes
publisher: QNAP Inc.
categories:
  - transformations
type: plugin
desc: Kong middleware to transform requests / responses, using Lua script.
description: |
    This is a Kong Plugin that transforms requests and responses depending on your own business requirements.
support_url: https://github.com/qnap-dev/kong-plugin-api-transformer/issues
source_code:  https://github.com/qnap-dev/kong-plugin-api-transformer
license_type: Apache-2.0
license_url: https://github.com/qnap-dev/kong-plugin-api-transformer/blob/master/LICENSE

kong_version_compatibility:
  community_edition:
    compatible:
      - 1.0.x
      - 1.1.x
      - 1.2.x
